---
kind: Service
apiVersion: v1
metadata:
  name: orch-kafka-0
spec:
  type: NodePort
  ports:
    - name: external
      port: 9094
      nodePort: 32090
  selector:
    statefulset.kubernetes.io/pod-name: orch-kafka-0
---
kind: Service
apiVersion: v1
metadata:
  name: orch-kafka-1
spec:
  type: NodePort
  ports:
    - name: external
      port: 9094
      nodePort: 32091
  selector:
    statefulset.kubernetes.io/pod-name: orch-kafka-1
---
kind: Service
apiVersion: v1
metadata:
  name: orch-kafka-2
spec:
  type: NodePort
  ports:
    - name: external
      port: 9094
      nodePort: 32092
  selector:
    statefulset.kubernetes.io/pod-name: orch-kafka-2
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: orch-kafka
data:
  override.sh: |
    #!/bin/bash

    export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    export KAFKA_BROKER_ID=$(echo ${HOSTNAME##*-})
    export KAFKA_LISTENERS=INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
    export KAFKA_ADVERTISED_LISTENERS=INTERNAL://$(hostname -f):9093,EXTERNAL://10.9.56.11:$((32090 + ${KAFKA_BROKER_ID}))
    export KAFKA_ZOOKEEPER_CONNECT=orch-zookeeper:2181
    export KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    export KAFKA_LOG_DIRS=/var/lib/kafka
    export KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    export KAFKA_AUTO_LEADER_REBALANCE_ENABLE=true
    export KAFKA_BACKGROUND_THREADS=10
    export KAFKA_COMPRESSION_TYPE=producer
    export KAFKA_DELETE_TOPIC_ENABLE=true
    export KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS=300
    export KAFKA_LEADER_IMBALANCE_PER_BROKER_PERCENTAGE=10
    export KAFKA_LOG_FLUSH_INTERVAL_MESSAGES=9223372036854775807
    export KAFKA_LOG_FLUSH_OFFSET_CHECKPOINT_INTERVAL_MS=60000
    export KAFKA_LOG_FLUSH_SCHEDULER_INTERVAL_MS=9223372036854775807
    export KAFKA_LOG_RETENTION_BYTES=-1
    export KAFKA_LOG_RETENTION_HOURS=672
    export KAFKA_LOG_ROLL_HOURS=168
    export KAFKA_LOG_ROLL_JITTER_HOURS=0
    export KAFKA_LOG_SEGMENT_BYTES=1073741824
    export KAFKA_LOG_SEGMENT_DELETE_DELAY_MS=60000
    export KAFKA_MESSAGE_MAX_BYTES=1000012
    export KAFKA_MIN_INSYNC_REPLICAS=1
    export KAFKA_NUM_IO_THREADS=10
    export KAFKA_NUM_NETWORK_THREADS=3
    export KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR=1
    export KAFKA_NUM_REPLICA_FETCHERS=1
    export KAFKA_OFFSET_METADATA_MAX_BYTES=4096
    export KAFKA_OFFSETS_COMMIT_REQUIRED_ACKS=-1
    export KAFKA_OFFSETS_COMMIT_TIMEOUT_MS=5000
    export KAFKA_OFFSETS_LOAD_BUFFER_SIZE=5242880
    export KAFKA_OFFSETS_RETENTION_CHECK_INTERVAL_MS=600000
    export KAFKA_OFFSETS_RETENTION_MINUTES=1440
    export KAFKA_OFFSETS_TOPIC_COMPRESSION_CODEC=0
    export KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS=50
    export KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
    export KAFKA_OFFSETS_TOPIC_SEGMENT_BYTES=104857600
    export KAFKA_QUEUED_MAX_REQUESTS=500
    export KAFKA_QUOTA_CONSUMER_DEFAULT=9223372036854775807
    export KAFKA_QUOTA_PRODUCER_DEFAULT=9223372036854775807
    export KAFKA_REPLICA_FETCH_MIN_BYTES=1
    export KAFKA_REPLICA_FETCH_WAIT_MAX_MS=500
    export KAFKA_REPLICA_HIGH_WATERMARK_CHECKPOINT_INTERVAL_MS=5000
    export KAFKA_REPLICA_LAG_TIME_MAX_MS=10000
    export KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES=65536
    export KAFKA_REPLICA_SOCKET_TIMEOUT_MS=30000
    export KAFKA_REQUEST_TIMEOUT_MS=30000
    export KAFKA_SOCKET_RECEIVE_BUFFER_BYTES=102400
    export KAFKA_SOCKET_REQUEST_MAX_BYTES=104857600
    export KAFKA_SOCKET_SEND_BUFFER_BYTES=102400
    export KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=true
    export KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS=30000
    export KAFKA_ZOOKEEPER_SET_ACL=false
    export KAFKA_BROKER_ID_GENERATION_ENABLE=true
    export KAFKA_CONNECTIONS_MAX_IDLE_MS=600000
    export KAFKA_CONTROLLED_SHUTDOWN_ENABLE=true
    export KAFKA_CONTROLLED_SHUTDOWN_MAX_RETRIES=3
    export KAFKA_CONTROLLED_SHUTDOWN_RETRY_BACKOFF_MS=5000
    export KAFKA_CONTROLLER_SOCKET_TIMEOUT_MS=30000
    export KAFKA_DEFAULT_REPLICATION_FACTOR=3
    export KAFKA_FETCH_PURGATORY_PURGE_INTERVAL_REQUESTS=1000
    export KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=300000
    export KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS=6000
    export KAFKA_INTER_BROKER_PROTOCOL_VERSION=2.1
    export KAFKA_LOG_CLEANER_BACKOFF_MS=15000
    export KAFKA_LOG_CLEANER_DEDUPE_BUFFER_SIZE=134217728
    export KAFKA_LOG_CLEANER_DELETE_RETENTION_MS=86400000
    export KAFKA_LOG_CLEANER_ENABLE=true
    export KAFKA_LOG_CLEANER_IO_BUFFER_LOAD_FACTOR=0.9
    export KAFKA_LOG_CLEANER_IO_BUFFER_SIZE=524288
    export KAFKA_LOG_CLEANER_IO_MAX_BYTES_PER_SECOND=1.7976931348623157E308
    export KAFKA_LOG_CLEANER_MIN_CLEANABLE_RATIO=0.5
    export KAFKA_LOG_CLEANER_MIN_COMPACTION_LAG_MS=0
    export KAFKA_LOG_CLEANER_THREADS=1
    export KAFKA_LOG_CLEANUP_POLICY=delete
    export KAFKA_LOG_INDEX_INTERVAL_BYTES=4096
    export KAFKA_LOG_INDEX_SIZE_MAX_BYTES=10485760
    export KAFKA_LOG_MESSAGE_TIMESTAMP_DIFFERENCE_MAX_MS=9223372036854775807
    export KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE=CreateTime
    export KAFKA_LOG_PREALLOCATE=false
    export KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS=300000
    export KAFKA_MAX_CONNECTIONS_PER_IP=2147483647
    export KAFKA_NUM_PARTITIONS=3
    export KAFKA_PRODUCER_PURGATORY_PURGE_INTERVAL_REQUESTS=1000
    export KAFKA_REPLICA_FETCH_BACKOFF_MS=1000
    export KAFKA_REPLICA_FETCH_MAX_BYTES=1048576
    export KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=10485760
    export KAFKA_RESERVED_BROKER_MAX_ID=1000
