---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orch-zookeeper
data:
  jvm.heap: "1G"
  tick: "2000"
  init: "10"
  sync: "5"
  client.cnxns: "60"
  snap.retain: "3"
  purge.interval: "0"
  admin.enableServer: 'false'
  client.port: '2181'
  data.dir: /var/lib/zookeeper
  election.port: '3888'
  log.dir: /var/log/kafka
  server.port: '2888'
  servers: orch-zookeeper-0.orch-zookeeper:2888:3888
  standaloneEnabled: 'false'
